### ISSUE TITLE
MSbar Masses Scale Variations

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#101]
In principle, even the running of the masses is at fixed order, and the contribution from missing higher order can be estimated by the running that follows from RGE.

This will estimate MHOU in the masses' anomalous dimension, and it is yet another different scale from renormalization and factorization scales.

It might be argued (*citation needed*) that if not varied on its own, it should be kept the same of renormalization scale.

**Comment by felixhekhorn** [comment]
Moved to https://github.com/NNPDF/eko/wiki/List-of-Possible-Future-Features
