### ISSUE TITLE
Versioning data format

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#106]
Since:
- we're now putting a lot of effort in the output format (see #105)
- multiple libraries will be able to read it (see #97)

we should definitely start to assign versions to it (see https://github.com/N3PDF/pineappl/issues/118).

Versions should be:
- written in all the files
- be easy to query (as easy as possible)
- not overwritten by a library that generates new ones (even if it's able to read them)

Ideally, instead of reading old versions with a new version of the library (that might generate incompatibilities, or severely limit upgrades), the form of backward compatibility should be to allow the new library to convert an old format to the new one, but refuse direct reading of an old format (that might have undefined behavior in general).

**Comment by AleCandido** [comment]
Partly addressed by #172.

It has not been completed yet. However, a new version of this issue has been spelled out in #175, adding relevant details about the version behavior. Should we close this as superseded? @felixhekhorn

**Comment by felixhekhorn** [comment]
Agreed
