### ISSUE TITLE
Exterminate `from_dict`

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#114]
At the moment, we've `from_dict` methods all over the place, that expect a runcard with all the elements they need, but not specifying which ones.
At LO they are recapped by `runner` (where most of these methods are used):
https://github.com/N3PDF/eko/blob/813bd656159cde5c5d176b54ca99139e2280cb44/src/eko/runner.py#L44-L55

The information that is thus passed down is very unclear, and changes in the runcard format might affect silently all these methods.

Since they are always using a small amount of parameters, I propose a close replacement, based on the idea of sections:
```py
bfd = interpolation.InterpolatorDispatcher(**operators_card["interpolation"])
```
This is somewhat a trade-off: it is not clear from the call which parameters are used (but it's clear that only one section is affected), and in any case can be determined by the callee (the signature of the function called).

**Comment by AleCandido** [comment]
@felixhekhorn I propose to close this as done, since it has been implemented in https://github.com/NNPDF/eko/pull/172

**Comment by felixhekhorn** [comment]
Agreedd
