### ISSUE TITLE
problems with scheme B scale variations

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#121]
in pineko we have a problem with scheme B scale variations https://github.com/N3PDF/pineko/pull/19 (we should move pineko to NNPDF to make @giacomomagni able to see it ...)

- our first guess was to remove the scale variations of the strong coupling to "no correction is applied here to the "resummation" scale," [as said by @AleCandido] - which we didn't do before (see [here](https://github.com/N3PDF/eko/blob/341e6323e680d2320ae4400da61c92a445160416/src/eko/evolution_operator/__init__.py#L278) ) and indeed we know that for scheme A = LHA paper shifting was correct (since we're matching there); this fix turns out to be not sufficient
- out of fun I tried to *invert* the scale ratio (xiev -> 1/xiev) and surprisingly enough this brought scheme B and C much closer: from 90% off to mostly O(10%) off
- then I started looking at the scheme B implementation of eko and there is something I don't understand: why is the [expanded correction](https://github.com/N3PDF/eko/blob/341e6323e680d2320ae4400da61c92a445160416/src/eko/scale_variations/expanded.py#L30) not similar to the [exponentiated correction](https://github.com/N3PDF/eko/blob/341e6323e680d2320ae4400da61c92a445160416/src/eko/scale_variations/exponentiated.py#L51) ? i.e. one has beta0 the other not?
- however, looking at Eq. 3.33 of MHOU I can't see an immediate error ...

PS: side note: https://github.com/N3PDF/eko/blob/341e6323e680d2320ae4400da61c92a445160416/doc/source/theory/pQCD.rst#L126
there is no such thing as a PDF set in eko - the "whole operator" is meant

**Comment by felixhekhorn** [comment]
- [ ] most likely a missing minus sign from Eq. 3.33
- [ ] in scheme B the starting scale has to be kept fixed (so no *effective* shifting - in practice we might do and undo the thing); in scheme A the current implementation is correct
- [ ] `pineko` need to request for scheme B the *central* scale (and not the shifted one as at the moment of writing is doing); effectively eko is takining fully care of the SV

**Comment by AleCandido** [comment]
> (we should move pineko to NNPDF to make @giacomomagni able to see it ...)

What if we made `pineko` public to begin with?

**Comment by giacomomagni** [comment]
It's already public! I'm able to see it :)

**Comment by AleCandido** [comment]
> (we should move pineko to NNPDF to make @giacomomagni able to see it ...)

What if we made `pineko` public to begin with?

**Comment by giacomomagni** [comment]
This should be closed right?

**Comment by AleCandido** [comment]
I definitely think so. @andreab1997 @felixhekhorn ?

**Comment by andreab1997** [comment]
> I definitely think so. @andreab1997 @felixhekhorn ?

Yes we can close this
