### ISSUE TITLE
Cut `banana` out of `ekobox`

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#122]
Maybe the solution is just a forth package, `ekobox` and `ekomark` will depend on it, but at least `ekobox` won't depend on `ekomark`, and we're sure will not depend on `banana`.

**Comment by felixhekhorn** [comment]
@scarlehoff we were thinking about this as a solution for the problems in https://github.com/NNPDF/nnpdf/pull/1529

**Comment by scarlehoff** [comment]
This is in the milestone for 0.9.4 (which has been reelased) but it is not closed. What is the status? (to know whether I have to update the conda recipe or not: https://github.com/conda-forge/eko-feedstock/pull/3)

**Comment by AleCandido** [comment]
The person that released v0.9.4 simply forgot to update the milestone (milestones in EKO have been just introduced, people are not familiar with them...). I'm updating it.

**Comment by felixhekhorn** [comment]
> The person that released v0.9.4 simply forgot to update the milestone (milestones in EKO have been just introduced, people are not familiar with them...). I'm updating it.

sorry :innocent:

**Comment by AleCandido** [comment]
No problem :)

**Comment by felixhekhorn** [comment]
the relevant PR is #226
