### ISSUE TITLE
ekobox dependencies

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#134]
as said by @AleCandido 

> I see: the problem was in the dependencies, because the package is always installed. The extras is only needed for extra dependencies, of course. But then `mark` and `box` have the same dependencies...
> 
> https://github.com/N3PDF/eko/blob/16b4606d877099ebf7b806f225a2f35adf881049/pyproject.toml#L68-L69

so someone just copied ... I think the correct `ekobox` dependencies are
- `click` https://github.com/N3PDF/eko/blob/16b4606d877099ebf7b806f225a2f35adf881049/src/ekobox/genpdf/cli.py#L6
- and `banana-hep` e.g. via https://github.com/N3PDF/eko/blob/16b4606d877099ebf7b806f225a2f35adf881049/src/ekobox/gen_theory.py#L5 (subject to #122 )

@AleCandido @andreab1997 do you agree?

the `ekomark` dependencies seem to be alright ...

**Comment by AleCandido** [comment]
Following the list of `import` inside `ekobox` for current `develop` branch.

If you strip:
- standard library
- local imports
- dependencies that are already present (e.g. `yaml`)
- and the other packages (i.e. `eko` and `ekomark`)

We remain with the two that you listed, + `lhapdf`.

Unfortunately, the dependency on `ekomark` reintroduces all the others, so we this issue depends on #122 (not the title, but the conclusion: we'd like `ekobox` not to depend on `banana`, so it should not depend also on `ekomark`).

```
gen_theory.py
2:import copy
4:import yaml
5:from banana.data import sql, theories
68:def import_theory_card(path):

genpdf/flavors.py
2:import copy
4:import numpy as np
6:from eko import basis_rotation as br

__init__.py
2:from ekomark import apply
4:from . import evol_pdf, gen_info, gen_op, gen_theory

evol_pdf.py
2:import pathlib
4:import eko
5:from eko import basis_rotation as br
6:from ekomark import apply
8:from . import gen_info, genpdf

genpdf/__init__.py
2:import copy
3:import pathlib
4:import shutil
6:import numpy as np
7:from banana import toy
9:from eko import basis_rotation as br
11:from . import export, flavors, load
128:        >>> from eko import basis_rotation as br
129:        >>> from ekobox.tools import genpdf
130:        >>> import numpy as np
188:    import lhapdf  # pylint: disable=import-error, import-outside-toplevel

genpdf/cli.py
6:import click
8:from . import generate_pdf, install_pdf

utils.py
2:import copy
4:import numpy as np

mock.py
2:import numpy as np

gen_op.py
2:import copy
4:import yaml
5:from banana.data import sql
7:from ekomark.data import operators
62:def import_op_card(path):

genpdf/export.py
2:import io
3:import pathlib
4:import re
6:import numpy as np
7:import yaml

gen_info.py
2:import copy
3:import math
5:from .genpdf import load

genpdf/load.py
2:import pathlib
4:import numpy as np
5:import yaml
29:    import lhapdf  # pylint: disable=import-error, import-outside-toplevel
56:    import lhapdf  # pylint: disable=import-error, import-outside-toplevel
```

**Comment by felixhekhorn** [comment]
The dependencies for `ekobox` are now reduced on master
https://github.com/NNPDF/eko/blob/cd96aa212a6656e3079bbd2af115868ff58101e9/pyproject.toml#L82
but we're missing `click` which is a dependencies - this breaks the `eko` CLI (which is not used by anyone :innocent: ) , but this also means the CLI of `genpdf` is broken when only installing with `eko[box]`; instead when installing also  `ekomark` you get `banana` and thus `click`

**Comment by AleCandido** [comment]
Can you fix it, please?
