### ISSUE TITLE
Work in a Temporary Folder

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#139]
Instead of using an archive at runtime, that is rather impractical, let's use a temporary folder.

The archive is only generated on save, and load when an EKO is instatiated.

See https://github.com/N3PDF/eko/pull/105#discussion_r925751448

- [x] encode q2 by bytes in filenames
- [x] add contextmanager á la `open()` (to and from tar), wrapping:
     - [x] function to open, extracting the tar
     - [x] function to close, compressing to tar
- [x] add CLI for conversion (almost a wrapper of `output.legacy.load_tar()`) in `ekobox`

**Comment by AleCandido** [comment]
Contrary to what I said before: the tar file location should be specified, but the temporary directory is always temporary, that is a detail (better not to expose it to the user, it will make code easier).

In any case, for the time being don't allow for directory specification,  if we will have a use case we will extend later.

**Comment by AleCandido** [comment]
@felixhekhorn I propose to close this as done, since the remaining part has been implemented in #172

**Comment by felixhekhorn** [comment]
Agreed
