### ISSUE TITLE
Allow user to choose also final scale FNS

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#149]
After the output rework #138 we should also open the possibility of not only specifying the target scale but also the target FNS, allowing for `nf=None` which determines the FNS from the atlas

**Comment by AleCandido** [comment]
This would be useful also for https://github.com/NNPDF/yadism/issues/166.

In general, we should trade `mugrid` for an `endpoints` list of `(mu, nf)` pairs, since we might want to have PDFs at the same scale in more schemes (or in overlapping regions anyhow).

**Comment by giacomomagni** [comment]
this is now possible right?
