### ISSUE TITLE
Runcards Dataclasses

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#153]
There are three very good reasons to move to dedicated classes for loading runcards:

1. having more control over the structure 
    - at the moment there is a spread usage, and unclear definition in the docs
2. getting rid of dictionaries and `from_dict` methods (see also #114)
3. sanitize before dump in a unique place
    - as we know since long, YAML is tricked by NumPy scalars, making them very complex objects

They have been initialized, but nothing relevant has actually been done:
https://github.com/NNPDF/eko/blob/2f2755c9f316976eeec68d11a150915f137ba43d/src/eko/runcards.py#L1-L60

The idea is to have a first attempt, with all the sanitation we are aware, and then incrementally improve it over time.

E.g. use also `dict` in place of `output.struct.Debug` or `output.struct.Configs` for the time being - later on we can also consider moving them to the `runcards` module itself.

**Comment by felixhekhorn** [comment]
Agreed
