### ISSUE TITLE
Tutorial problems

### ISSUE THREAD

**Issue by cschwan** [NNPDF/eko#155]
I'm trying to follow the [first tutorial for EKO](https://eko.readthedocs.io/en/latest/overview/tutorials/dglap.html), but I ran into the following problem:

```
In [2]: from banana.data.theories import default_card as th_card
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [2], line 1
----> 1 from banana.data.theories import default_card as th_card

ModuleNotFoundError: No module named 'banana.data'
```

Note that I also ran `pip install banana` without which it fails trivially.

**Comment by felixhekhorn** [comment]
Conjectured solution: we need: `pip install eko[mark]` instead of the `pip install eko` written [here](https://eko.readthedocs.io/en/latest/overview/tutorials/index.html)

> Note that I also ran pip install banana without which it fails trivially.

_our_ `banana` module is actually inside the `banana-hep` package - which gets installed by ekomark: https://github.com/NNPDF/eko/blob/01efee1d27d215e895dd055debff8905af3d548c/pyproject.toml#L70

**Comment by cschwan** [comment]
Installing ekomark doesn't work on my computer:

```bash
$ pip install ekomark
ERROR: Could not find a version that satisfies the requirement ekomark
ERROR: No matching distribution found for ekomark
```

**Comment by felixhekhorn** [comment]
yes, sorry I was unclear again ... the command you have to run is: `pip install eko[mark]`

this will (among other stuff) install the `ekomark` _module_ and the `banana-hep` _package_ (containing the `banana` _module_)

**Comment by cschwan** [comment]
Oh I see - I didn't realize that square brackets are allowed as a Python package name - my mistake! That solves the problem described above for me.

**Comment by AleCandido** [comment]
Indeed, the proper way to update the docs should be:
```sh
pip install 'eko[mark]'
```
since some shells (e.g. zsh) interpret the square brackets...
