### ISSUE TITLE
Collinear Parton Dynamics Beyond DGLAP

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#158]
https://arxiv.org/pdf/2210.10061.pdf

looks quite interesting - I wonder whether we could do something similar? (I haven't read or understood it fully)

**Comment by AleCandido** [comment]
1. they got an equation for the "Track function" not PDFs
2. non-linear means you can not solve with linear operator -> trash EKO
3. EKO itself is a package/library to solve DGLAP, we said from the beginning, so we have nothing "beyond DGLAP" in our initial design; there is nothing bad in refactoring, but adding features over features would bloat our software (and having all the features from the beginning in a consistent design is exactly the reason why we decided to replace the pre-existing software with EKO)

I would close as totally not relevant for EKO

**Comment by felixhekhorn** [comment]
accepted
