### ISSUE TITLE
Test scale variations expanded against exponentiated

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/eko#201]
At the moment the test `scheme_diff` in `[/scale_variations/test_expanded.py](https://github.com/NNPDF/eko/pull/191/files/591dfbb78381a5aa043b7103c8605767bc074a2d#diff-69e13373b89b52fc6ae55e1044c7029153d1724257ae27f74352b9cb8311ebef) is not really checking the difference between scheme A and B (i.e exponentiated vs expanded). However we know how to do the proper test because we have all the terms in a mathematica notebbok in pineko ([here](https://github.com/NNPDF/pineko/pull/68)). While the actual expressions for scale variations have been checked against this notebook, the test has not been updated consistently yet (for lack of time). We should
do the proper thing as soon as possible. @AleCandido @felixhekhorn @giacomomagni

**Comment by felixhekhorn** [comment]
Note that in #222 the SV behaviour was re-derived and changed (and, e.g., in effect for `exponentiated` $\xi_F$ flipped on it's head)
