### ISSUE TITLE
Make MSbar masses running

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#209]
@giacomomagni can you please have a look here
https://github.com/NNPDF/eko/blob/658bfe6e020add54848911347f804d053b675492/tests/eko/runner/test_legacy.py#L34-L41

most likely I'm misconfiguring something, but I'm not sure ...

PS: this I found while hunting for #192

**Comment by giacomomagni** [comment]
sorry @felixhekhorn on which branch should I try?

**Comment by felixhekhorn** [comment]
master

**Comment by giacomomagni** [comment]
It looks the initial quark scales are not set:

```
reference_running.<locals>.ReferenceRunning(value=2.0, scale=nan)
```

Adding something as:
```
    theory_card.quark_masses.c.scale = 2
    theory_card.quark_masses.b.scale = 4.5
    theory_card.quark_masses.t.scale = 173.07
```
should solve the issue.
