### ISSUE TITLE
Ekobox info file does not update AlphaS_Qs and AlphaS_Vals from template

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/eko#228]
Looking at https://github.com/NNPDF/eko/blob/73e438ef3c406144e2879b3b4d5430a82b143718/src/ekobox/info_file.py#LL57C5-L57C63
it seems that we are not updating the alpha_Q and alpha_values from the INFO file template. Do you know why?
@AleCandido @felixhekhorn 

@giacomomagni this is the reason of the problem you faced with `evolven3fit_new`

**Comment by AleCandido** [comment]
I guess you should the one who knows...

![image](https://user-images.githubusercontent.com/10830876/227183002-8ebd10d4-d615-46ec-ad70-588b0321cf80.png)

**Comment by andreab1997** [comment]
I already checked and I got confused that is why I asked :)

**Comment by andreab1997** [comment]
And I opened the issue also to remind myself to fix this problem

**Comment by andreab1997** [comment]
In any case in a sense I was right in the sense that since I don't have the operator in the function I cannot get the alpha values. So probably I either need to pass the operator to this function (which I would not) or update the entries after.

**Comment by AleCandido** [comment]
Ah, wait, now that I think about it, we dropped the alpha values also from the operator (for the reason you know well), so you should recompute them using EKO :P

Instantiate the `Couplings` class and fill the values by yourself ^^

**Comment by andreab1997** [comment]
Oh yes you are right I was silly :)
