### ISSUE TITLE
LHA SV fails for smallest x in CI

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#241]
we still have the 100% error [in github](https://github.com/NNPDF/eko/actions/runs/4606070102/jobs/8138911316#step:7:421):
```
Computing for theory=45286e9, ocard=cc12964 and pdf=ToyLH ...
Compute external result

Log added, hash=2e5273d953ef355a2f48badae3729333e94e6808ae941048e2e2e943771b0e63


 ─── 
  S  
 ─── 
               x       Q2         eko     eko_error         LHA  percent_error
0   1.000000e-07  10000.0    0.000000  0.000000e+00  251.422304    -100.000000
1   1.000000e-06  10000.0  132.769958  1.641839e-04  133.133286      -0.272906
```
but I cannot reproduce this locally
```
In [2]: dfl(-1)
Out[2]: 

- theory: `45286e92f0fbedc3ed4a84b47547190efc4bde84583e5782716a5c5c70448aed`
- obs: `8beae75234d8ba49de7079e5f76d3916dd810708d31bb54f85505faf1c470055`
- using PDF: *ToyLH*

S
               x       Q2         eko     eko_error         LHA  percent_error
0   1.000000e-07  10000.0  250.741696  3.320808e-04  251.422304      -0.270703
1   1.000000e-06  10000.0  132.769958  1.641844e-04  133.133286      -0.272906
```
Note that the obs hash is not the same ... I seem to remember to have seen this before ... @giacomomagni ? or @t7phy ?

_Originally posted by @felixhekhorn in https://github.com/NNPDF/eko/issues/238#issuecomment-1495732624_

**Comment by giacomomagni** [comment]
Having rerun this locally after recompiling everything from scratch, I confirm I'm not able to reproduce the error.

**Comment by felixhekhorn** [comment]
@giacomomagni can you confirm my obs hash?

**Comment by felixhekhorn** [comment]
> EDIT: Note that ls(o) is currently broken:

I think this should have been fixed in https://github.com/NNPDF/eko/pull/231 - and indeed I can not reproduce it. Can you check if you regenerate the DB it works also for you? (backup the old if you do not want to loose it - maybe a simple rename there can save you)

**Comment by felixhekhorn** [comment]
> but `obs` is different from both of you...

now, this is strange ... I wonder if there is some platform dependency (on floats?)? moreover, the visible digits match exactly - between the two of us starting from the first point and with the CI after that ... actually, we do not agree on the error, although I think we should ... (quad is fully deterministic)

**Comment by giacomomagni** [comment]
> I think this should have been fixed in #231 - and indeed I can not reproduce it. Can you check if you regenerate the DB it works also for you? (backup the old if you do not want to loose it - maybe a simple rename there can save you)

Oh yes true I still had an old db, now it works. 
Maybe that can explain also the hash difference. Let me run again.

**Comment by giacomomagni** [comment]
The obs hash is still different

**Comment by felixhekhorn** [comment]
The actual problem discussed here has been resolved see https://github.com/NNPDF/eko/actions/runs/4948469063/jobs/8849225663 . For the new problem of non-comparable hashes I opened #267
