### ISSUE TITLE
pole structure NNLO time-like ad

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#263]
@t7phy I know you copied the time-like anomalous dimension from A. Vogt - but I wonder how useful is this condition:
https://github.com/NNPDF/eko/blob/fb46d8b6a7588465de581ad7e31270f36696a7ee/src/ekore/anomalous_dimensions/unpolarized/time_like/as3.py#L268
are we ever hitting that case? i.e. can we remove this branching?

Moreover, the function also contains explicit $1/N$ (which already makes $N=0$ unstable) and even $1/(N-1)$ ... speaking of, can you remind me about the pole structure of the time-like anomalous dimensions? because in the space-like case `nsv` does neither have a pole at $N=1$ nor at $N=0$ (because number conservation is defined there)

cc @enocera

**Comment by t7phy** [comment]
Hi @felixhekhorn 

For the 1st question, the answer is that we do not really know whether we will need that condition or not, that is why it's preserved as was given by Vogt.

For the second question, it's my understanding that Vogt's functions use simple harmonic sums like s1, s2, s3 but the other harmonic sums are made with the combination of the required terms. It is in these combinations where the terms like 1/N or 1/N-1 are used.

**Comment by felixhekhorn** [comment]
Ciao @t7phy 

> For the 1st question, the answer is that we do not really know whether we will need that condition or not, that is why it's preserved as was given by Vogt.

well, the question whether you need this or not is directly related to the pole structure; to be specific: if there is already a pole at $N=0$ there is no need to regularize that point ...

> For the second question, it's my understanding that Vogt's functions use simple harmonic sums like s1, s2, s3 but the other harmonic sums are made with the combination of the required terms. It is in these combinations where the terms like 1/N or 1/N-1 are used.

of course they are made by those terms, because they are the natural building blocks. The exact NNLO expressions might be more complicated, but the Vogt strategy is to approximate them with s-es and polynomials - however, he always preserves the *physics features*, i.e. the large-N behaviour and the pole structure of the leading pole. Please check the relevant papers for the pole structure - they should be discussed there, because, as said, they correspond to actual physics. And then double check the pole structure on the actual expression e.g. with Mathematica.

**Comment by giacomomagni** [comment]
Just for my curiosity, do you know why is this term replaced by `zeta2` in the small N limit? 

```
NI = 1/n;
NM = n - 1;
NMI = 1/NM;
S1M = S[1,n] - NI;
B1M = -S1M * NMI;
Series[B1M, {n,0,1}]
```
gives:
 $-1/n -1 + (-1 + \zeta_2) n + \mathcal{O}(n^2)$

**Comment by felixhekhorn** [comment]
Mmm, actually, you're right ... there seems to be something fishy with the $N$ definition:

- `Series[Sum[1/j, {j, 1, n}]/n, {n, 0, 0}]` -> $\pi^2/6 = \zeta_2$
- and, of course, then `Series[Sum[1/j, {j, 1, n - 1}]/(n - 1), {n, 1, 0}]` -> $\pi^2/6 = \zeta_2$

so I guess the condition should be near $N=1$, no?

if you agree, this would confirm that the condition (as is) is never triggered (as it is wrong)

**Comment by giacomomagni** [comment]
True at `N=1` it would make sense. But why do we have this mismatch? 
Can this be a sign that in the reference paper a different convention for Mellin has been used ?
@t7phy

**Comment by t7phy** [comment]
I still have to go through the paper, haven't been able to yet due to courses and exams. Will do it asap.

**Comment by felixhekhorn** [comment]
@t7phy if you can please resolve this issue
