### ISSUE TITLE
Hash computation seems not unique (across systems?)

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#267]
The purpose of computing hashes inside `banana` is to boil down the full information to make it traceable - however, it seems that the hash is *not* unique across systems as was revealed in #241.  At some point I had even locally the problem that the navigator comparison was empty, but the hash was still different.

For the case at hand we had:
- `ocard=cc12964` in the CI
- `- obs: 8beae75234d8ba49de7079e5f76d3916dd810708d31bb54f85505faf1c470055` locally for myself
- `- obs: 5d279b7c4222fc5f9b2858f7438e69a683a0030ea3a41c1093be921e2ae0f25b` locally for @giacomomagni 

something which just came to my mind: we might of course also depend on the Python version - however, that would not explain my local hickup ...

**Comment by AleCandido** [comment]
I do not believe we actually depend on the Python version, since the hash function should be fixed.

However, this seems more of a `banana` issue rather than an `eko`/`ekomark` one.

**Comment by felixhekhorn** [comment]
Agreed -> https://github.com/N3PDF/banana/issues/33
