### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#304]
https://github.com/NNPDF/eko/blob/969e795fed400210fb2a42b276fe8a234199a337/doc/source/theory/N3LO_ad.rst?plain=1#L135

The minusses should be plusses, no?

**Comment by felixhekhorn** [comment]
Correct in the paper by the way

**Comment by giacomomagni** [comment]
True, thanks for spotting it. 
Fixed in cc1b872663f097218fd4de0e1d5f7fa03e075958
