### ISSUE TITLE
Is `matching_order` correctly determined?

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#322]
Actually here I think we have introduced a bug.
`matching_order`  follows `PTO` (ie is 2 for NNLO) so here we should subtract one, once doing the default, no?

_Originally posted by @giacomomagni in https://github.com/NNPDF/eko/pull/299#discussion_r1384385630_

**Comment by felixhekhorn** [comment]
hmm? to me it seems [the LHA benchmarks have passed](https://github.com/NNPDF/eko/actions/runs/6458211610/job/17531433642), which should test the default - and also the N3LO benchmarks seemed alright, which should test the overwriting ... or do you mean we can no longer access the N3LO matching?

**Comment by niclaurenti** [comment]
Hi @giacomomagni and @felixhekhorn , but looking at 

https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/evolution_operator/operator_matrix_element.py#L66

`matching_order` must be 2 at NNLO:
It should be $delta_{ij}$ at LO, $a_s A^{(1)}$ at NLO and $a_s^2 A^{(2)}$ at NNLO.

**Comment by giacomomagni** [comment]
Indeed, we `matching_oder` should have a shift wrt to `order`.
@felixhekhorn  I think this bug affects only the "new runcards", while in the LH benchmarks run through the old format no ?

**Comment by felixhekhorn** [comment]
Okay, so you are worried about this line specifically:
https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/runner/parts.py#L93
then maybe I agree with you, there is a bug - do you agree as well @niclaurenti ? When fixing this, we should provide also a unit test

**Comment by niclaurenti** [comment]
Ok @giacomomagni you are right. Sorry for doubting.
Previously I did a test with the "old runcards" (via apfel_bench.py) and it was ok.
Now I did another one with the new ones and in `build_ome` we have `matching_order=(3,0)` at NNLO.

The point in which it must be changed is:

https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/evolution_operator/operator_matrix_element.py#L167C17-L167C17

**Comment by giacomomagni** [comment]
> Ok @giacomomagni you are right. Sorry for doubting. Previously I did a test with the "old runcards" (via apfel_bench.py) and it was ok. Now I did another one with the new ones and in `build_ome` we have `matching_order=(3,0)` at NNLO.
> 
> The point in which it must be changed is:
> 
> https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/evolution_operator/operator_matrix_element.py#L167C17-L167C17

mmm wait, now I disagree. We should just adjust the lines modified in that PR. 
In particular: 

https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/runner/parts.py#L92C1-L93

**Comment by felixhekhorn** [comment]
> The point in which it must be changed is:
> 
> https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/evolution_operator/operator_matrix_element.py#L167C17-L167C17

I agree with @giacomomagni:

1. we need to change there 
2. on top we should drop https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/runner/legacy.py#L81-L82 because after https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/runner/legacy.py#L46 `new_theory` has `matching_order` https://github.com/NNPDF/eko/blob/10f0733635c012ce7e1f0fd4cdfc497619292830/src/eko/io/runcards.py#L216C14-L216C28 (this is the reason why "old style" was working)

**Comment by niclaurenti** [comment]
Yes I agree, I've read Felix's comment after posting mine
