### ISSUE TITLE
Remove photon and top from LHAPDF grid if they are not active

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/eko#329]
Would it be possible not to dump the photon and top entries into the LHAPDF grids if they are not active? This should affect everything but the mixed QED fit. The reason is that some random MC programs will crash just because of this and as a matter of fact I've already encountered two.

**Comment by AleCandido** [comment]
In principle, you could always erase from it.

We never finished turning `genpdf` into a full-fledged toolbox, but you can check if stripping distributions is already supported there, and otherwise add it yourself (it should be pretty simple)

**Comment by giacomomagni** [comment]
Actually, looking at the code the easiest fix, that will solve your problem would be to change the pids list passed here: 

https://github.com/NNPDF/nnpdf/blob/e470c7e73490f3d4725dde6813aba2a2de018b69/n3fit/src/evolven3fit_new/evolve.py#L184-L186

So we can drop 22 if there is no QED and top according to `MaxNfPdf`. 
If you agree, I suggest to move to the issue there and I can draft a PR.

**Comment by Radonirinaunimi** [comment]
Thanks both!

> Actually, looking at the code the easiest fix, that will solve your problem would be to change the pids list passed here:
> 
> https://github.com/NNPDF/nnpdf/blob/e470c7e73490f3d4725dde6813aba2a2de018b69/n3fit/src/evolven3fit_new/evolve.py#L184-L186
> 
> So we can drop 22 if there is no QED and top according to `MaxNfPdf`. If you agree, I suggest to move the issue there and I can draft a PR.

This is indeed the best place to apply the modification. I am not sure though what people think about this. If @scarlehoff thinks that this is a reasonable, then if you @giacomomagni could open a PR to address this that'd be great (otherwise I can also do so).

**Comment by scarlehoff** [comment]
Yes, LHAPDF actually just puts 0 when it doesn't find a flavour so it should be equivalent.

However
> The reason is that some random MC programs will crash just because of this

which MC programs are these? Wouldn't this be a bug as well to be reported to them? Or is it expected behavior? (we can fix it in our side since it wouldn't change anything ofc but still)

**Comment by Radonirinaunimi** [comment]
Closing this as it was indeed a limitation in the MC codes (which for now has to be fixed by the user).
