### ISSUE TITLE
polarized setup

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/eko#40]
as I come myself from an polarized environment, I'd really like to sell it to this community too - meaning I'd like to implement it - should be easy after all ... but for that very reason, we could leave this also to someone external, to test this claimed "easiness"

**Comment by AleCandido** [comment]
In APFEL it is done by:
- `RSLintegralsQCDPol` in `RSLintegralsQCD.f`
- `integrandsQCDPol` in `integrandsQCD.f`

**Comment by felixhekhorn** [comment]
https://arxiv.org/pdf/2108.12807.pdf - they are doing some corrections to DGLAP?
