### ISSUE TITLE
Plots on website

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#86]
A huge number of plots can be produced to extensively document `eko` options.

- all solutions
- several matching options
- scale variations
- all benchmarks
- ...

To show all of them the paper is not the proper place, but not even is the documentation.

So a good option is to put them on [eko website](https://n3pdf.github.io/eko/) (i.e. GitHub Pages).

**Comment by felixhekhorn** [comment]
Moved to https://github.com/NNPDF/eko/wiki/List-of-Possible-Future-Features
