### ISSUE TITLE
ekobox plots

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/eko#87]
- [ ] import plots utils from a number of sources:
  - `ekomark`
  - IC paper
  - `eko` paper
- [ ] always use `eko` paper style for plots
- [ ] extend the mechanism of plots runcards:
  - functions should take dictionaries as inputs, not file paths (more general, wrappers might be provided, but they would be extremely thin)
  - provide as many defaults as possible: in principle one should give only a PDF set as input (better not to choose a default here, to remain a bit agnostic) and a plot should be produced
  - provide example runcards as a library (similar to [`matplotlib.style.library`](https://matplotlib.org/stable/api/style_api.html#matplotlib.style.matplotlib.style.library))
  - we should choose meaningful names for plots

**Comment by felixhekhorn** [comment]
Moved to https://github.com/NNPDF/eko/wiki/List-of-Possible-Future-Features
